sonar.projectKey=com.job:scheduler
sonar.projectName=scheduler
sonar.sourceEncoding=UTF-8
sonar.java.source=17
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=target/**,**/*Application.java
